# Generated by Django 2.1.5 on 2019-01-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
