# Generated by Django 2.1.5 on 2019-01-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agregar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extensiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('version', models.IntegerField()),
                ('fecha', models.DateField()),
                ('extensiones', models.ManyToManyField(blank=True, to='programa.Extensiones')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agregar.Persona')),
            ],
        ),
    ]
