# Generated by Django 2.1.5 on 2019-01-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
